### ISSUE TITLE
Retrieve page lock status

### ISSUE THREAD

**Issue by danieltharp** [pxdnbluesoul/scuttle#14]
This will probably need a rewrite of some sort to 2stacks and additional credentials stored in .env.

**Comment by emmiegit** [comment]
It appears that Wikidot leaks whether a page is locked or if you merely can't edit because you're a guest:

**Guest:** http://www.scp-wiki.net/scp-4447
![image](https://user-images.githubusercontent.com/8848022/75299350-d41bec00-5802-11ea-9051-8a3ba2590366.png)

**Locked:** http://www.scp-wiki.net/scp-173
![image](https://user-images.githubusercontent.com/8848022/75299374-df6f1780-5802-11ea-97cc-90047d3d582f.png)

**Comment by emmiegit** [comment]
Call from `ajax-module-connector.php`:

**Guest:**
```json
{
    "status": "no_permission",
    "mode": "page",
    "message": "Sorry, you can not edit this page. Only members of this site, owner (creator) of this page, site administrators and perhaps selected moderators are allowed to do it. <a href=\"#action:login\">Sign in as Wikidot user</a>",
    "CURRENT_TIMESTAMP": 1582676113,
    "callbackIndex": "2"
}

```

**Locked:**
```json
{
    "status": "no_permission",
    "mode": "page",
    "message": "Page is locked and you cannot edit it: please contact your site admin",
    "CURRENT_TIMESTAMP": 1582676052,
    "callbackIndex": "3"
}
```

**Comment by emmiegit** [comment]
It looks like edit sends the following:
```yaml
page_id: [id]
mode: page
wiki_page: [slug]
moduleName: edit/PageEditModule
callbackIndex: [??]
wikidot_token7: [token]
```

**Comment by emmiegit** [comment]
So scraping by message content isn't great, since the error won't be in English for INT wikis.

However, there is something we can use to distinguish between the two messages:

```json
{
    "status": "no_permission",
    "mode": "page",
    "message": "\u62b1\u6b49\uff01\u60a8\u4e0d\u80fd \u7f16\u8f91\u672c\u9875\u3002\u53ea\u6709 \u7f51\u7ad9\u6210\u5458, \u672c\u9875\u62e5\u6709\u8005\uff08\u5efa\u7acb\u8005\uff09, \u7f51\u7ad9\u7ba1\u7406\u5458\u4e0e\u7248\u4e3b \u53ef\u4ee5\u8fd9\u4e48\u505a\u3002 <a href=\"#action:login\">\u767b\u5165\u4e3a Wikidot \u7528\u6237</a>",
    "CURRENT_TIMESTAMP": 1582676762,
    "callbackIndex": "2"
}
```

If you're a guest, it asks you to login. We can search for `Wikidot` or `#action:login` in the message and determine if the page is locked or not.

**Comment by emmiegit** [comment]
Noting for thread lock status the same principle can be used:

**Guest:**
![image](https://user-images.githubusercontent.com/8848022/75400009-eca40900-58cb-11ea-838e-e4d61b3f5343.png)

**Locked:**
![image](https://user-images.githubusercontent.com/8848022/75400001-e57cfb00-58cb-11ea-9046-e1766c794cb8.png)

```json
{
    "status": "no_permission",
    "message": "Sorry, you can not add new post in this thread. Only members of this site, site administrators and perhaps selected moderators are allowed to do it. <a href=\"#action:login\">Sign in as Wikidot user</a>",
    "CURRENT_TIMESTAMP": 1582762358,
    "callbackIndex": "2"
}
```

Also allows for the same `#action:login` check.

**Comment by emmiegit** [comment]
Clicking "new post" requires the following:

```yaml
postId: [null]
threadId: [id]
moduleName: forum/sub/ForumNewPostFormModule
callbackIndex: [??]
wikidot_token7: [token]
```
